Feature/fix search
surroundaustralia/Prez pull request #103
Opened 2022-07-13 06:21 UTC by jamiefeiss

Fixes VocPrez concept search issues relating to named graphs & HTTPS.

Fixes SpacePrez CQL search issues relating to feature title predicates. 

Adds support for providing multiple predicates for a CQL search property with an optional preference order.

2022-07-13 07:29 UTC, nicholascar commented on prez/services/spaceprez_service.py
> +                BIND(COALESCE(?dcDesc, COALESCE(?def, ?sdoDesc)) AS ?desc)
You don't have to do pair-wise COALESCing, you can just do `COALESE(?dcDesc, ?def, ?sdoDesc)`

2022-07-13 07:30 UTC, nicholascar commented on prez/services/spaceprez_service.py
> +                FILTER(lang(?prefLabel) = "" || lang(?prefLabel) = "en" || lang(?prefLabel) = "en-AU")
Do we really have any `@en-AU` data? I've see the handing of this in a few places in Prez code but I don't really seeing any data that would require it.

2022-07-13 07:33 UTC, nicholascar commented on prez/services/spaceprez_service.py
> +                            a dcat:Dataset . }}
I think these class matches are redundant when matching on a given predicate & object like `?d dcterms:identifier "{dataset_id}"^^xsd:token`. As in I don;t think they benefit query speed since the triplestore will simply follow the POS index: from predicate to object to subject. 

Don't do anything about this here but in the future, feel free to leave classing matches out unless they assist in understanding the query.

2022-07-13 07:34 UTC, nicholascar requested changes
Looks good Jamie: just a couple of minor comments that are really more prettier code comments than change requests to functionality!

2022-07-14 01:29 UTC, jamiefeiss commented on prez/services/spaceprez_service.py
> +                BIND(COALESCE(?dcDesc, COALESCE(?def, ?sdoDesc)) AS ?desc)
Thanks. Updated this in the most recent commit

2022-07-14 01:44 UTC, nicholascar approved these changes

2022-07-14 02:21 UTC, recalcitrantsupplant commented
Also checked - no issues. merging

2022-07-14 02:21 UTC, merged