Feature/byo profile
surroundaustralia/Prez pull request #54
Opened 2022-05-18 15:15 UTC by recalcitrantsupplant

Changes to use profiles defined in data

2022-05-23 23:41 UTC, nicholascar commented on prez/app.py
> +    while True:
Please put a comment in here to describe what this while loop is doing

2022-05-23 23:42 UTC, nicholascar commented on prez/app.py
> +            url = urlparse(SPACEPREZ_SPARQL_ENDPOINT)
Make this conditional on enabled Prezes

2022-05-23 23:48 UTC, nicholascar commented on prez/profiles/generate_profiles.py
> +@cached(cache=Cache.MEMORY, ttl=3600)
See if there is an LRU configuration here

2022-05-23 23:50 UTC, nicholascar commented on prez/profiles/spaceprez_profiles.py
> +
Remove this

2022-05-23 23:51 UTC, nicholascar commented on prez/profiles/spaceprez_default_profiles.ttl
> +PREFIX altr-ext: <http://www.w3.org/ns/dx/conneg/altr-ext#>
Need a vocprez_default_profiles.ttl

2022-05-23 23:52 UTC, nicholascar commented on prez/renderers/renderer.py
> +    def _make_rdf_response(self, feature_uri, graph: Graph) -> Response:
Move this to Feature renderer

2022-05-24 00:06 UTC, nicholascar commented on prez/routers/spaceprez_router.py
> +@cached(cache=Cache.MEMORY, ttl=3600)
Change this one - time not good here

2022-05-24 00:13 UTC, nicholascar commented on prez/routers/spaceprez_router.py
>      "/dataset/{dataset_id}/collections/{collection_id}/items/{feature_id}",
Push this caching to the underlying function (that contains the triplestore SPARQL call)

2022-05-24 00:16 UTC, nicholascar commented on prez/services/spaceprez_service.py
> +      ?coll dcterms:identifier "{collection_id}"^^xsd:token ;
Get URI for FC first as it's token may not be unique across the whole SpacePrez instance

2022-05-24 00:17 UTC, nicholascar commented on prez/services/spaceprez_service.py
> +      ?coll dcterms:identifier "{collection_id}"^^xsd:token ;
Basically we need Dataset context per FC

2022-05-24 00:18 UTC, nicholascar commented on prez/services/spaceprez_service.py
> +@cached(cache=Cache.MEMORY, ttl=3600)
Timed cache no-no

2022-05-24 00:19 UTC, nicholascar commented on prez/services/spaceprez_service.py
> +                OPTIONAL {{
Replace with Jamie's static props query text

2022-05-24 00:20 UTC, nicholascar commented on prez/services/sparql_utils.py
> +  ?profile a prof:Profile OPTIONAL {
Add in OPTIONAL for skos:Concept too for VP

2022-05-24 00:22 UTC, nicholascar requested changes
Just make all the changes as discussed!

2022-05-25 02:32 UTC, recalcitrantsupplant commented on prez/app.py
> +    while True:
Added comment in code

2022-05-25 02:37 UTC, recalcitrantsupplant commented on prez/app.py
> +            url = urlparse(SPACEPREZ_SPARQL_ENDPOINT)
Added check for each enabled prez

2022-05-25 03:03 UTC, recalcitrantsupplant commented on prez/services/sparql_utils.py
> +  ?profile a prof:Profile OPTIONAL {
Added

2022-05-25 03:04 UTC, recalcitrantsupplant commented on prez/services/spaceprez_service.py
> +@cached(cache=Cache.MEMORY, ttl=3600)
Switched to https://github.com/aio-libs/async-lru with limit of 20 for everything
This should cover the first page for features, feature collections, datasets

2022-05-25 03:07 UTC, recalcitrantsupplant commented on prez/services/spaceprez_service.py
> +      ?coll dcterms:identifier "{collection_id}"^^xsd:token ;
Updated to:
```
    SELECT (COUNT(?f) as ?count)
    WHERE {{
        ?dataset dcterms:identifier "{dataset_id}"^^xsd:token ;
            rdfs:member / dcterms:identifier "{collection_id}"^^xsd:token ;
                                         rdfs:member ?f .
```

2022-05-25 03:31 UTC, recalcitrantsupplant commented on prez/routers/spaceprez_router.py
>      "/dataset/{dataset_id}/collections/{collection_id}/items/{feature_id}",
Moved all caching to endpoint functions. Calls using URI or ID both use the endpoint functions

2022-05-25 03:31 UTC, recalcitrantsupplant commented on prez/routers/spaceprez_router.py
> +@cached(cache=Cache.MEMORY, ttl=3600)
All caching changed to LRU

2022-05-25 03:32 UTC, recalcitrantsupplant commented on prez/profiles/generate_profiles.py
> +@cached(cache=Cache.MEMORY, ttl=3600)
All caching changed to LRU

2022-05-25 06:29 UTC, recalcitrantsupplant commented on prez/services/spaceprez_service.py
> +                OPTIONAL {{
done

2022-05-26 08:25 UTC, recalcitrantsupplant commented on prez/profiles/spaceprez_profiles.py
> +
removed 2x python profile files

2022-05-26 08:25 UTC, recalcitrantsupplant commented on prez/profiles/spaceprez_default_profiles.ttl
> +PREFIX altr-ext: <http://www.w3.org/ns/dx/conneg/altr-ext#>
not yet implemented - python file will be in use for now.

2022-05-26 23:17 UTC, recalcitrantsupplant commented
I think we're good to go. Stuffed up a rebase - so the commit history is bloated.

2022-05-27 04:07 UTC, nicholascar requested changes
OK, some very minor comments there. The only substantial one is about the PREZ namespace: did you define that in data and I just missed it? If it's a tiny ontology, can you please show me?

2022-05-27 04:07 UTC, nicholascar commented on prez/renderers/spaceprez/spaceprez_dataset_list_renderer.py
> +# from profiles.spaceprez_profiles import dcat, dd
Remove not comment! Git history will save us if needed...

2022-05-27 04:07 UTC, nicholascar commented on prez/renderers/spaceprez/spaceprez_feature_collection_renderer.py
> +# from profiles.spaceprez_profiles import oai, geo
Remove not comment

2022-05-27 04:07 UTC, nicholascar commented on prez/renderers/spaceprez/spaceprez_feature_list_renderer.py
> +# from profiles.spaceprez_profiles import oai, dd
Remove not comment

2022-05-27 04:07 UTC, nicholascar commented on prez/renderers/spaceprez/spaceprez_feature_renderer.py
> +# from profiles.spaceprez_profiles import oai, geo, gas
Remove not comment

2022-05-27 04:07 UTC, nicholascar commented on prez/renderers/spaceprez/spaceprez_home_renderer.py
> +# from profiles.spaceprez_profiles import oai
Remove not comment

2022-05-27 04:07 UTC, nicholascar commented on prez/routers/spaceprez_router.py
> +PREZ = Namespace("https://surroundaustralia.com/prez/")
Is this _really_ necessary?

2022-05-27 04:07 UTC, nicholascar commented on prez/services/spaceprez_service.py
> +    PREFIX dcterms: <http://purl.org/dc/terms/>
Can you please just tidy up the formatting of this query a bit?

2022-05-27 04:18 UTC, recalcitrantsupplant commented
> OK, some very minor comments there. The only substantial one is about the PREZ namespace: did you define that in data and I just missed it? If it's a tiny ontology, can you please show me?

It is only in 'prez/profiles/spaceprez_default_profiles.ttl', and on the router page, no ontology at present

2022-05-27 04:20 UTC, recalcitrantsupplant commented on prez/routers/spaceprez_router.py
> +PREZ = Namespace("https://surroundaustralia.com/prez/")
it can also be a string, in which case the profiles will read:

<http://www.opengis.net/spec/ogcapi-features-1/1.0/req/oas30>
    rdfs:label "OpenAPI 3.0" ;
    dcterms:description "The OpenAPI Specification (OAS) defines a standard, language-agnostic interface to RESTful APIs which allows both humans and computers to discover and understand the capabilities of the service without access to source code, documentation, or through network traffic inspection." ;
    dcterms:identifier "oai";
    a prof:Profile ;
    altr-ext:constrainsClass
        **"homepage" ,
        "conformance" ,**
        geo:Feature ,
        geo:FeatureCollection ;
    altr-ext:hasResourceFormat "text/turtle", "application/ld+json", "application/rdf+xml", "text/html" ;
    altr-ext:hasDefaultResourceFormat "text/html" ;
.

2022-05-27 04:21 UTC, recalcitrantsupplant commented on prez/renderers/spaceprez/spaceprez_home_renderer.py
> +# from profiles.spaceprez_profiles import oai
done

2022-05-27 04:24 UTC, recalcitrantsupplant commented on prez/services/spaceprez_service.py
> +    PREFIX dcterms: <http://purl.org/dc/terms/>
done

2022-05-27 04:28 UTC, recalcitrantsupplant commented on prez/renderers/spaceprez/spaceprez_dataset_list_renderer.py
> +# from profiles.spaceprez_profiles import dcat, dd
done

2022-05-27 04:28 UTC, recalcitrantsupplant commented on prez/renderers/spaceprez/spaceprez_conformance_renderer.py
> +    # profiles = {"oai": oai}
done

2022-05-27 04:29 UTC, recalcitrantsupplant commented on prez/renderers/spaceprez/spaceprez_feature_list_renderer.py
> +# from profiles.spaceprez_profiles import oai, dd
done

2022-05-27 04:30 UTC, recalcitrantsupplant commented on prez/renderers/spaceprez/spaceprez_feature_collection_renderer.py
> +# from profiles.spaceprez_profiles import oai, geo
done

2022-05-29 23:29 UTC, nicholascar commented on prez/profiles/generate_profiles.py
> +# @alru_cache(maxsize=20)
If not needed, please remove

2022-05-29 23:31 UTC, nicholascar approved these changes

2022-05-29 23:36 UTC, recalcitrantsupplant commented on prez/profiles/generate_profiles.py
> +# @alru_cache(maxsize=20)
removed below

2022-05-29 23:36 UTC, merged